spring:
  application:
    name: microservice-sonsumer-moive-ribbon
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://user1:pwd123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}